spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    ##open-in-view=false: true
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    ##org.hibernate.SQL: DEBUG
    co.abacus: DEBUG
